version: '3'

services:
  postgres-compose:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@901256"
      POSTGRES_DB: nossa-cdc
    ports:
      - "15432:5432"
    volumes:
      - C:/Users/lucas.castro/Documents/workspace-micronout/data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucaspontes140@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "@901256"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge