micronaut:
  application:
    name: nossaCasaDoCodigo

#-banco de dados
datasources:
  default:
    url: jdbc:postgresql://localhost:15432/nossa-cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: "@901256"
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
jackson:
  serialization:
    writeDatesAsTimestamps=false: